name: to_do
description: A local database based flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.0 # Slide able button for delete
  get: ^4.6.5 # state management
  shared_preferences: ^2.2.0 # Local database
  smooth_page_indicator: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
